"""add column

Revision ID: fb3982e495a8
Revises: f40eed13ab95
Create Date: 2025-12-15 20:53:23.816315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb3982e495a8'
down_revision: Union[str, Sequence[str], None] = 'f40eed13ab95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history', sa.Column('title', sa.String(), nullable=False))
    op.add_column('history', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('history', 'created_at')
    op.drop_column('history', 'title')
    # ### end Alembic commands ###
